services:
  merkle-pay:
    build:
      context: .
      dockerfile: apps/merkle-pay/Dockerfile
    container_name: merkle-pay-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - TURNSTILE_SECRET_KEY=${TURNSTILE_SECRET_KEY}
    networks:
      - merkle-network

  # This service now only builds the dashboard assets and exits
  merkle-dashboard:
    build:
      context: .
      dockerfile: apps/merkle-dashboard/Dockerfile
    volumes:
      - dashboard-dist:/app/apps/merkle-dashboard/dist

  caddy:
    build:
      context: .
      dockerfile: caddy/Dockerfile
    container_name: caddy-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    environment:
      - DOMAIN=${DOMAIN}
    networks:
      - merkle-network # Caddy still needs the network to proxy to merkle-pay
    volumes:
      # Mount the built dashboard assets from the named volume (read-only)
      - dashboard-dist:/srv/dashboard:ro
      - ./caddy/data:/data
      - ./caddy/config:/config
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
    # Ensure dashboard build completes before Caddy starts
    depends_on:
      - merkle-dashboard

networks:
  merkle-network:
    driver: bridge

# Define the named volume for dashboard assets
volumes:
  dashboard-dist:
